version: "3"

services:
  app:
    depends_on:
      - mongo
      - nginx
    environment:
      PORT: "5000"
      MONGO_CONNECTION_STRING: mongodb://mongo/database
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    container_name: express-ts-demo
    command: node dist/app.js

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    expose:
      - "80"
    ports:
      - "80:80"

  mongo:
    image: mongo
    volumes:
      - "./mongodb/data/db:/mongodb/data/db"
