apiVersion: apps/v1
kind: Deployment

metadata:
  name: express-ts-demo-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: express-ts-demo

  template:
    metadata:
      labels:
        app: express-ts-demo
    spec:
      containers:
        - name: express-ts-demo
          image: express-ts-demo:v1.3
          args:
            - node
            - dist/app.js
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username

            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database_url

            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database

            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: production
