apiVersion: v1
kind: Service
metadata:
  name: mongo-clusterip-service

spec:
  type: ClusterIP
  selector:
    app: mongo-deployment
  
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
